### ISSUE TITLE
Add line breaks in HTML

### ISSUE THREAD

**Issue by stain** [Language-Research-Technology/ro-crate-html-lite#2]
As the RO-Crate HTML Lite output is particularly suited for long-term storage, use newlines after each </div>  to make the HTML also somewhat maintainable if it needs to be fixed for future browsers.

**Comment by ptsefton** [comment]
It has too many line breaks already! I think I need to remove rather than add whitespace at this point

**Comment by ptsefton** [comment]
Removed some linebreaks - generated HTML looks reasonably neat now
