### ISSUE TITLE
Thesis crate context not resolving 

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-html-lite#5]
The thesis crate @stain was having problems with does render, but the reference to https://w3id.org/ro/crate/1.2-DRAFT/context seems to be causing the context terms to not be resolve so all the terms show up in the "other" category 

See  `test_data/thesis`

**Comment by ptsefton** [comment]
@stain if you change the profile URL to 1.1 it works as expected but we will try to fix -- something happening in the RO-Crate-js library @alvinsw

**Comment by alvinsw** [comment]
Fixed the code by calling resolveContext after creating a crate
