### ISSUE TITLE
Rather than falling back to a built in layout in the lib, fetch the default layout over the 'net as well

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-html-lite#7]
Issue here is that the default Mode is very large so we might want to to extract that and publish it separately

**Comment by rosanna-smith** [comment]
dynamic-layout branch now pulls the default layout from https://raw.githubusercontent.com/Language-Research-Technology/crate-o/refs/heads/main/src/lib/components/default_layout.json
